/*****************************    STATEMENT TYPES      *********************/

export const GET_ALL_STATEMENTS_START = "GET_ALL_STATEMENTS_START";
export const GET_ALL_STATEMENTS_SUCCESS = "GET_ALL_STATEMENTS_SUCCESS";
export const GET_ALL_STATEMENTS_FAILURE = "GET_ALL_STATEMENTS_FAILURE";

export const GET_STATEMENT_BY_ID_START = "GET_STATEMENT_BY_ID_START";
export const GET_STATEMENT_BY_ID_SUCCESS = "GET_STATEMENT_BY_ID_SUCCESS";
export const GET_STATEMENT_BY_ID_FAILURE = "GET_STATEMENT_BY_ID_FAILURE";

export const GET_MY_STATEMENT_BY_ID_START = "GET_MY_STATEMENT_BY_ID_START";
export const GET_MY_STATEMENT_BY_ID_SUCCESS = "GET_MY_STATEMENT_BY_ID_SUCCESS";
export const GET_MY_STATEMENT_BY_ID_FAILURE = "GET_MY_STATEMENT_BY_ID_FAILURE";

export const GET_MY_STATEMENTS_START = "GET_MY_STATEMENTS_START";
export const GET_MY_STATEMENTS_SUCCESS = "GET_MY_STATEMENTS_SUCCESS";
export const GET_MY_STATEMENTS_FAILURE = "GET_MY_STATEMENTS_FAILURE";

export const CREATE_STATEMENT_START = "CREATE_STATEMENT_START";
export const CREATE_STATEMENT_SUCCESS = "CREATE_STATEMENT_SUCCESS";
export const CREATE_STATEMENT_FAILURE = "CREATE_STATEMENT_FAILURE";

export const CHANGE_STATEMENT = "CHANGE_STATEMENT";

export const NEW_STATEMENT_NOTIFICATION = "NEW_STATEMENT_NOTIFICATION";
export const SET_NOTIFICATIONS_FROM_LOCALSTORAGE =
  "SET_NOTIFICATIONS_FROM_LOCALSTORAGE";

/*****************************    USER TYPES      *********************/

export const GET_USER_BY_ID_START = "GET_USER_BY_ID_START";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_BY_ID_FAILURE";

export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";

export const GET_LEADERS_START = "GET_LEADERS_START";
export const GET_LEADERS_SUCCESS = "GET_LEADERS_SUCCESS";
export const GET_LEADERS_FAILURE = "GET_LEADERS_FAILURE";

/*****************************    SIDEBAR TYPES     *********************/

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";

/*****************************    DASHBOARD TYPES     *********************/

export const GET_STATEMENTS_INFO_START = "GET_STATEMENTS_INFO_START";
export const GET_STATEMENTS_INFO_SUCCESS = "GET_STATEMENTS_INFO_SUCCESS";
export const GET_STATEMENTS_INFO_FAILURE = "GET_STATEMENTS_INFO_FAILURE";

/*****************************    AUTH TYPES     *********************/

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOCK_PROFILE_START = "LOCK_PROFILE_START";
export const LOCK_PROFILE_SUCCESS = "LOCK_PROFILE_SUCCESS";
export const LOCK_PROFILE_FAILURE = "LOCK_PROFILE_FAILURE";

export const UNLOCK_PROFILE_START = "UNLOCK_PROFILE_START";
export const UNLOCK_PROFILE_SUCCESS = "UNLOCK_PROFILE_SUCCESS";
export const UNLOCK_PROFILE_FAILURE = "UNLOCK_PROFILE_FAILURE";

export const LOGOUT = "LOGOUT";

/*****************************    SMS TYPES     *********************/

export const VERIFY_SMS_START = "VERIFY_SMS_START";
export const VERIFY_SMS_SUCCESS = "VERIFY_SMS_SUCCESS";
export const VERIFY_SMS_FAILURE = "VERIFY_SMS_FAILURE";

export const SEND_SMS_CODE_START = "SEND_SMS_CODE_START";
export const SEND_SMS_CODE_SUCCESS = "SEND_SMS_CODE_SUCCESS";
export const SEND_SMS_CODE_FAILURE = "SEND_SMS_CODE_FAILURE";

/*****************************    MESSAGE TYPES     *********************/

export const GET_MESSAGES_START = "GET_MESSAGES_START";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAILURE = "GET_MESSAGES_FAILURE";

export const GET_MY_MESSAGE_BY_ID_START = "GET_MY_MESSAGE_BY_ID_START";
export const GET_MY_MESSAGE_BY_ID_SUCCESS = "GET_MY_MESSAGE_BY_ID_SUCCESS";
export const GET_MY_MESSAGE_BY_ID_FAILURE = "GET_MY_MESSAGE_BY_ID_FAILURE";

export const SEND_MESSAGE_START = "SEND_MESSAGE_START";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

export const NEW_MESSAGE_NOTIFICATION = "NEW_MESSAGE_NOTIFICATION";
export const SET_MSG_NOTIFICATIONS_FROM_LOCALSTORAGE =
  "SET_MSG_NOTIFICATIONS_FROM_LOCALSTORAGE";